import {test,assert} from './test-kit.mjs';
import {collectSnapshot,deriveTaskName,applyAutomaticNames} from '../src/reader/reader.mjs';
const r=(texts)=>({thread:{id:'t',turns:texts.map((text,i)=>({id:'u'+i,items:[{type:'userMessage',id:'m'+i,content:[{type:'text',text}]}]}))}});
test('auto-name-new-runtime-turn-bypasses-still-fresh-source-cache',async()=>{const cache=new Map();let texts=['请整理采购验收清单。'],reads=0;const c={request:async(m)=>m==='thread/list'?{data:[{id:'t',name:null,updatedAt:1}]}:(reads++,r(texts))};await collectSnapshot(c,{cache});texts.push('请翻译设备维护手册。');await collectSnapshot(c,{cache,priorityIds:['t'],expectedTurns:{t:'u1'}});assert.equal(reads,2);assert.equal(cache.get('t').name.turnId,'u1');assert.equal(cache.get('t').name.parts[0].text,'设备维护手册');});
test('auto-name-failure-pending-unrecognized-visible-without-stale-name',()=>{const task={threadId:'t',updatedAt:1,desktopRuntime:{turnId:'u0'}};assert.equal(applyAutomaticNames([task],new Map())[0].nameStatus,'pending');assert.equal(applyAutomaticNames([task],new Map([['t',{updatedAt:1,readStatus:'unavailable'}]]))[0].nameStatus,'unavailable');const name=deriveTaskName(r(['继续']),'t');assert.equal(applyAutomaticNames([task],new Map([['t',{updatedAt:1,name}]]))[0].nameStatus,'unrecognized');});
test('auto-name-negative-new-request-removes-previous-positive-task',()=>{const n=deriveTaskName(r(['请整理采购验收清单。','不要整理采购验收清单。']),'t');assert.equal(n.status,'unrecognized');});
test('auto-name-unclosed-context-block-not-treated-as-user-request',()=>{const n=deriveTaskName(r(['<environment_context>\n请整理私人密码清单。']),'t');assert.equal(n.status,'unrecognized');});
test('auto-name-restart-and-bounded-batch-cost',()=>{const input=r(['请帮青岚科技核对供应商付款台账。',...Array.from({length:14},()=>('继续。'+ '说明内容。'.repeat(1300)))]);const started=performance.now();for(let i=0;i<8;i++){const a=deriveTaskName(input,'t'),b=deriveTaskName(input,'t');assert.deepEqual(a,b);}assert.ok(performance.now()-started<500,'local naming blocks state loop over 500ms');});
test('auto-name-source-recovery-retries-after-failure-with-no-ui',async()=>{let clock=1000000;const old=Date.now;Date.now=()=>clock;try{const cache=new Map();let failing=true;const c={request:async(m)=>{if(m==='thread/list')return {data:[{id:'t',updatedAt:1}]};if(failing)throw Error('private');return r(['请翻译设备维护手册。']);}};await collectSnapshot(c,{cache,priorityIds:['t']});assert.equal(cache.get('t').readStatus,'unavailable');failing=false;clock+=16000;await collectSnapshot(c,{cache,priorityIds:['t']});assert.equal(cache.get('t').name?.status,'ready');}finally{Date.now=old;}});
