async page => {
const out=[];const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const metrics=()=>{const dock=document.querySelector('.dock'),body=document.querySelector('.task-body');const br=body.getBoundingClientRect();return {width:dock.getBoundingClientRect().width,height:dock.getBoundingClientRect().height,pageOverflow:document.documentElement.scrollWidth>innerWidth,bodyOverflow:body.scrollWidth>body.clientWidth+1,bodyClient:body.clientHeight,bodyScroll:body.scrollHeight,allVisible:[...document.querySelectorAll('.task')].every(e=>e.getBoundingClientRect().bottom<=br.bottom+1),missing:!document.querySelector('.missing .stage')&&!document.querySelector('.missing .deadline'),sample:document.querySelector('.sample').textContent.includes('虚构排版样例'),font:parseFloat(getComputedStyle(document.querySelector('h2')).fontSize)}};
for(const [v,w,h] of [['a',390,560],['b',420,520]]){
 await page.setViewportSize({width:w,height:h});await page.goto('http://127.0.0.1:44319/'+v+'.html');await page.evaluate(()=>document.fonts.ready);const normal=await page.evaluate(metrics);out.push({variant:v,state:'normal',...normal});await page.screenshot({path:'output/playwright/'+v+'-normal.png'});
 const colors=await page.evaluate(()=>{function rgb(s){return (s.match(/[\d.]+/g)||[]).slice(0,3).map(Number)}function L(c){return c.map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4}).reduce((a,x,i)=>a+x*[.2126,.7152,.0722][i],0)}const items=[];for(const e of document.querySelectorAll('.sample,.company,.deadline,.pending,h1,h2,.stage strong,.stage-name,.next,.next>span,.metrics span,.group-label,.bottom,.shortcut')){let p=e,bg;while(p){const s=getComputedStyle(p).backgroundColor;if(s!=='rgba(0, 0, 0, 0)'&&s!=='transparent'){bg=s;break}p=p.parentElement}bg=bg||'rgb(255,255,255)';const fg=getComputedStyle(e).color;const ls=[L(rgb(fg)),L(rgb(bg))].sort((a,b)=>b-a);items.push({text:e.textContent.slice(0,18),ratio:(ls[0]+.05)/(ls[1]+.05)})}return items});out.push({variant:v,state:'contrast',minRatio:Math.min(...colors.map(x=>x.ratio)),below:colors.filter(x=>x.ratio<4.5)});
 await page.setViewportSize({width:320,height:h});out.push({variant:v,state:'320',...await page.evaluate(metrics)});await page.screenshot({path:'output/playwright/'+v+'-320.png'});
 const before=await page.locator('h2').first().evaluate(e=>parseFloat(getComputedStyle(e).fontSize));await page.evaluate(()=>document.documentElement.style.fontSize='32px');const doubled=await page.evaluate(metrics);out.push({variant:v,state:'200percent',...doubled,fontDoubled:doubled.font===before*2});await page.screenshot({path:'output/playwright/'+v+'-200percent.png'});
 await page.evaluate(()=>{document.documentElement.style.fontSize='16px';document.querySelector('h2').textContent='校对《示例公司关于本年度超长期债券募集说明书财务数据与附注逐项一致性检查工作副本》';});
 out.push({variant:v,state:'longChinese',...await page.evaluate(metrics),title:await page.locator('h2').first().evaluate(e=>({wrap:getComputedStyle(e).overflowWrap,ellipsis:getComputedStyle(e).textOverflow,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth}))});await page.screenshot({path:'output/playwright/'+v+'-long.png'});
 await page.evaluate(()=>document.querySelector('.task-body').innerHTML='<p>虚构排版样例：尚无可展示任务。</p>');out.push({variant:v,state:'empty',horizontalOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});
 await page.evaluate(()=>document.querySelector('.sample').textContent='虚构排版样例 · 离线提示布局');out.push({variant:v,state:'offline-layout-only',horizontalOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});await page.screenshot({path:'output/playwright/'+v+'-empty-offline.png'});
}
await page.setViewportSize({width:990,height:810});await page.goto('http://127.0.0.1:44319/');await page.screenshot({path:'output/playwright/compare-checked.png',fullPage:true});
return {kind:'static-browser-layout-only',results:out,errors};
}
